### ISSUE TITLE
Student at Mdh in Eskilstuna 

### ISSUE THREAD

**Issue by Jezperlofberg** [ATholin/MDHAutoBooker#127]
I found this project really interesting. I’m a student at the other campus of Mdh that’s really tired of having to manage bookings at midnight every time a room might be needed for my studies. So, my question is really how hard a further implementation of the Eskilstuna rooms would be for this project, I believe these rooms are in the same system (kronox, mdh). And especially how hard it would be for a student that has zero to no experience in PHP and HTML programming. 

Or maybe this is just a suggestion for a further implementation. ;)

**Comment by ATholin** [comment]
Hey @Jezperlofberg!

Great suggestion. Adding support for Eskilstuna rooms was not much an issue, especially since the [original project ](https://github.com/Roslund/GroupRoomMaffia/) was quite well structured.

You should now be able to see the Eskilstuna rooms by selecting it on the applicable pages. Let me know if you have any issues.
